[theme]
primaryColor = "#1E3A8A"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1E3A8A"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
